### ISSUE TITLE
Qt integration fails 

### ISSUE THREAD

**Issue by Ihebdhouibi** [elsampsa/valkka-examples#5]
I am using this project as my starting point https://github.com/elsampsa/valkka-examples/tree/master/example_projects/basic

main1 function of basic/main.py suits my needs so I reused its code to create my filterchain, IPC etc

Trying to integrate my qt dashboard fails,  while the program is running, at the console level, everything is fine, I am recieving frames printing infos and so on, but Qt dashboard never launched.

Here is my code 

```
class Dashboard(QtWidgets.QMainWindow):

       def setupGUI(self): # my qt GUI 
       def __init__(self, address, parent_None):
                # Filterchain code 
                # ipc loop
                while True:
                # multiplex intercom from two multiprocess
                         rlis = [rgb_pipe, mp4_pipe_fd]
                         r, w, e = safe_select(rlis, [], [], timeout=1)

                         if rgb_pipe in r:
                         # there is an incoming message object from the rgb process
                                msg = rgb_pipe.recv()
                                print("MainProcess Dashboard: message from rgb process", msg)
                         if mp4_pipe_fd in r:
                         # there is an incoming message object from the frag mp4 process
                                msg = mp4_pipe.recv()
                                print("MainProcess Dashboard: message from frag-MP4 process", msg)

                         if len(r) < 1:
                               # Dashboard process is alive
                               # print("Dashboard process is alive")
                                pass

                except KeyboardInterrupt:
                          print("Terminating the program !! You stupid shit head pressed ctrl + c ")
                          break
```

**Comment by elsampsa** [comment]
Hi,

- Please update to the latest versions
- The Qt examples, the example project and the multiprocessing framework have all been reorganized - they were a bit confusing, to say the least
- Lot's of information and a link to an article about the multiprocessing framework have been added to the docs
- Issue/ticket templates have been added to this repo (**)

Let's see if that helps you (if you're still into this..).  Unfortunately your ticket does not have enough information for me to make anything of it at the moment.   I could simply reply to the title of your ticket with "It doesn't fail for me!", so..

.. if you still feel like you need help, file another ticket and follow the ticket templates (**) I have created (they show up when you create a new ticket).
